spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/blackjack

  r2dbc:
    url: r2dbc:mysql://localhost:3307/blackjack
    username: blackjack
    password: blackjack

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3307/blackjack
    user: blackjack
    password: blackjack
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs